version: '3.9'

services:
  geth:
    build:
      args:
        - VERSION=${VERSION}
      context: ./geth
      dockerfile: Dockerfile
    command:
      --http
      --http.api
      "eth,net,web3"
      --http.addr=0.0.0.0
      --http.vhosts=*
      --http.corsdomain=*
      --ws
      --ws.origins=*
      --ws.addr=0.0.0.0
      --ws.api
      "eth,net,web3"
      --graphql
      --graphql.corsdomain=*
      --graphql.vhosts=*
      --datadir
      "/chaindata"
      --syncmode=${SYNC_MODE:-fast}
      --gcmode=${GARBAGE_COLLECTION_MODE:-full}
      ${EXTRA_ARGS:-}
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    stop_signal: SIGINT
    stop_grace_period: 2m
    volumes:
      - ${DATA_DIR}:/chaindata
