version: '3.9'

services:
  geth:
    build:
      args:
        - VERSION=${VERSION}
      context: ./geth
      dockerfile: Dockerfile
    command: ${ARGUMENTS}
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    ports:
      - 30303:30303
      - 30303:30303/udp
      - ${RPC_PORT}:8545
      - ${WEBSOCKET_PORT}:8546
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    volumes:
      - ${DATA_DIR}:/.ethereum
